### ISSUE TITLE
doesn't install extra dependencies which causes errors

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [NightZan999/TheImperialGod#17]
Downloading https://files.pythonhosted.org/packages/9b/51/9d049faaf6c45d9c600c8a5dac5bd30d2333653a5acaf4ac3d0bf572c610/praw-7.1.0.tar.gz (21.3MB)
    99% |████████████████████████████████| 21.3MB 8.5MB/s eta 0:00:01 Killed

**Comment by Envel-Nikita-Gutsenkov** [comment]
full

`pip install -r requirements.txt
Collecting asyncio (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/da/54/054bafaf2c0fb8473d423743e191fcdf49b2c1fd5e9af3524efbe097bafd/asyncio-3.4.3.tar.gz
Collecting discord.py (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz
Collecting praw (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9b/51/9d049faaf6c45d9c600c8a5dac5bd30d2333653a5acaf4ac3d0bf572c610/praw-7.1.0.tar.gz (21.3MB)
    99% |████████████████████████████████| 21.3MB 5.2MB/s eta 0:00:01Killed`

**Comment by Envel-Nikita-Gutsenkov** [comment]
and if 
`python bot.py
  File "bot.py", line 52
    async def on_ready():
        ^
SyntaxError: invalid syntax`

**Comment by NightZan999** [comment]
Have you downloaded the latest zip AKA version 1 which I uploaded? That is the most stable source as configuring praw is hard and I have put the instructions there. @Envel-Nikita-Gutsenkov is this a pip server that your running this on?

**Comment by NightZan999** [comment]
Because some pip servers have problems with modules which tend to have more bugs. Example: bluefox hosting actually has a problem with asyncio! And some pip servers have problems with praw

**Comment by NightZan999** [comment]
Ight I figured out why this is happening @Envel-Nikita-Gutsenkov see when you download discord.py in the text you sent. It doesn't install aiohttp or urllib3 or any other modules that the bot requires. 

In a pip server when anyone tries `pip freeze requirements.txt` that creates a requirements.txt with all the dependencies needed. In **that version of the requirements.txt it forces the download of aiohttp and other such modules. By default when installing discord.py it should install all these dependencies too. As a fix, try `pip freeze requirements.txt`** and first delete the old requirements.txt. 

Then it should make a new one with all the dependencies, **now when installing it should actually go through all these other modules and then discord.py because in your pip server or cmd it doesn't install other dependencies!**

Let me know if this actually doesn't work

**Comment by Envel-Nikita-Gutsenkov** [comment]
I don't quite understand, but it doesn't seem to work. can't install exactly `praw` even if I do it manually via `pip install praw`

**Comment by Envel-Nikita-Gutsenkov** [comment]
if delete "requirements.txt" and write "pip freeze requirements.txt" then a new one is not created

**Comment by NightZan999** [comment]
@Envel-Nikita-Gutsenkov, okay now I will update the requirements.txt to its needs in v1.2 wait for like a week before I get the latest version out. I will update the requirements.txt as well.
